# Global Settings
SCREEN_WIDTH = 1000
HALF_SCREEN = SCREEN_WIDTH / 2
SCREEN_HEIGHT = 600
BALL_STARTING_SPEED = 0.02  # default 0.02
BALL_STARTING_YPOS = -200
PADDLE_STARTING_YPOS = -250
PADDLE_STRETCH = 10
GAME_TITLE = "Breakout!"
BRICK_ROW_COLORS = ["#F4EDCC", "#A4CE95", "#6196A6", "#5F5D9C"]
WALL_OFFSET = 10
STARTING_BALL_COUNT = 4

# Scoreboard settings
FONT = ("Arial", 30, "normal")
BIG_FONT = ("Arial", 60, "normal")

ALIGNMENT = "center"

BRICK_WIDTH = 3.0
BRICK_HEIGHT = 1.0
BRICK_WIDTH_PX = 70