# Global Settings
SCREEN_WIDTH = 1000
HALF_SCREEN = SCREEN_WIDTH // 2
SCREEN_HEIGHT = 600
BALL_STARTING_SPEED = 0.025  # default 0.025
BALL_STARTING_YPOS = -200


RANDOM_BALL_SPEEDS = (4, 5, 6)
DEFAULT_BALL_SPEED = 5

PADDLE_STARTING_YPOS = -250
PADDLE_STRETCH = 10
GAME_TITLE = "Breakout!"
BRICK_ROW_COLORS = ["#F4EDCC", "#A4CE95", "#6196A6", "#5F5D9C"]
WALL_OFFSET = 10
STARTING_BALL_COUNT = 4

SCOREBOARD_POSITION = 50

BG_COLOR = "black"
PADDLE_COLOR = "white"

# Scoreboard settings
FONT = ("Arial", 30, "normal")
BIG_FONT = ("Arial", 60, "normal")

ALIGNMENT = "center"

BRICK_WIDTH = 3.0
BRICK_HEIGHT = 1.0
BRICK_WIDTH_PX = 70
BRICK_COLLISION_WIDTH = 43    # 43 compensates for the round ball hitting brick corners

BRICK_SPACE_FROM_TOP_OF_WINDOW = 100

POINTS_PER_BRICK = 10

GAME_OVER_TEXT = "Game Over! Spacebar to play again"
GAME_START_TEXT = "Press the Spacebar to begin"

PADDLE_MOVE_SPEED = 20
BRICK_HEIGHT_PX = 20

# Calculate screen edges
SCREEN_TOP = (SCREEN_HEIGHT // 2) - WALL_OFFSET
SCREEN_RIGHT = HALF_SCREEN - WALL_OFFSET - 10
SCREEN_LEFT = -HALF_SCREEN + WALL_OFFSET
SCREEN_BOTTOM = -(SCREEN_HEIGHT // 2) - 100  # 100 PX BELOW SCREEN BOTTOM
PADDLE_TOP = PADDLE_STARTING_YPOS + 20

